name: recur_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.69.2
  charts_flutter: ^0.12.0
  table_calendar: ^3.0.0
  firebase_core: ^2.25.4
  firebase_auth: ^4.19.3
  cloud_firestore: ^4.15.4
  uuid: ^4.2.1
  confetti: ^0.7.0
  shared_preferences: ^2.1.0
  flutter_local_notifications: ^14.0.0
  connectivity_plus: ^4.0.0
  internet_connection_checker: ^1.0.0
  fluttertoast: ^8.0.8
  provider: ^6.0.0
  url_launcher: ^6.1.7



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.10.0"


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/recur.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
